### ISSUE TITLE
Server could not find CRD

### ISSUE THREAD

**Issue by andrewrynhard** [aporeto-inc/trireme-csr#27]
See https://github.com/aporeto-inc/trireme-kubernetes/issues/148

**Comment by bvandewalle** [comment]
Thanks for reporting @andrewrynhard . The main issue seem closed. I will be closing this one once the pr https://github.com/aporeto-inc/trireme-kubernetes/pull/147 gets addressed

**Comment by mheese** [comment]
@bvandewalle @andrewrynhard I'm closing this now as we merged the mentioned PR
